app: tobeit-backend
service: backend
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-southeast-1
  websocketsApiName: websockets-api
  websocketsApiRouteSelectionExpression: $request.body.action

functions:
  http:
    handler: handler.handler
    events:
      - httpApi: "*"

  websocket:
    handler: handler.websocket
    events:
      - websocket:
          route: $disconnect
      - websocket:
          route: $connect
      - websocket:
          route: $default
    timeout: 10

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  serverless-offline:
    lambdaPort: 5001
    httpPort: 5000
    websocketPort: 6000
    useChildProcesses: true
